// Generated by CoffeeScript 1.6.3
(function() {
  var YMDParser, parser;

  YMDParser = require("./lib/index");

  parser = new YMDParser;

  parser = new YMDParser;

  parser.generateGrammar();

  parser.printGrammar();

}).call(this);
