// Generated by CoffeeScript 1.6.3
(function() {
  var YMDParser, parser;

  YMDParser = require("./lib/index");

  parser = new YMDParser;

  parser.loadFile("test.md", function() {
    var ret;
    return ret = this.parseMarkdown(function(success) {
      if (!success) {
        throw Error("error parsing markdown");
      }
      return console.log(this.toHtml());
    });
  });

}).call(this);
